version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/my-app
    ports:
      - "5173:5173"
  
  backend:
    build:
      context: ./backend/my-nest
    ports:
      - "4000:4000"
  
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
